---
proxy-groups:
- name: SERVER-FALLBACK
  type: fallback
  disable-udp: false
  use:
  - PP-Umum
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: SERVER-LOADBALANCE
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - PP-Umum
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: BEST-PING
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  use:
  - PP-Umum
- name: SERVER-UMUM
  type: select
  disable-udp: false
  use:
  - PP-Umum
  proxies:
  - SERVER-FALLBACK
  - SERVER-LOADBALANCE
- name: SERVER-GAME
  type: select
  disable-udp: false
  use:
  - PP-Umum
  proxies:
  - SERVER-LOADBALANCE
- name: SERVER-SOSMED
  type: select
  disable-udp: false
  use:
  - PP-Umum
  proxies:
  - SERVER-FALLBACK
  - SERVER-LOADBALANCE
- name: SERVER-SPEEDTEST
  type: select
  disable-udp: false
  use:
  - PP-Umum
  proxies:
  - SERVER-LOADBALANCE
#
proxy-providers:
  PP-Umum:
    type: file
    path: "./proxy_provider/pp-umum.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
#
#rule-providers:
#  RP-Game:
#    type: file
#    behavior: classical
#    path: "./rule_provider/mlbb.yaml"
#
rules:
- AND,((NETWORK,udp),(OR,((DST-PORT,443),(GEOSITE,youtube)))),REJECT
#- GEOIP,GOOGLE,SERVER-GOOGLE
#- GEOSITE,GOOGLE,SERVER-GOOGLE
- GEOSITE,rule-gaming,SERVER-GAME
#- RULE-SET,RP-Game,SERVER-GAME
#- GEOSITE,rule-indo,SERVER-UMUM
- GEOSITE,rule-sosmed,SERVER-SOSMED
- GEOSITE,rule-streaming,SERVER-SOSMED
#- GEOIP,id,SERVER-UMUM
- GEOIP,facebook,SERVER-SOSMED
- GEOIP,netflix,SERVER-SOSMED
- GEOIP,telegram,SERVER-SOSMED
- GEOIP,twitter,SERVER-SOSMED
- GEOSITE,rule-speedtest,SERVER-SPEEDTEST
- MATCH,GLOBAL